#!/bin/csh -f
# ========== Copyright Header Begin ==========================================
# 
# OpenSPARC T1 Processor File: build_gates
# Copyright (c) 2006 Sun Microsystems, Inc.  All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES.
# 
# The above named program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License version 2 as published by the Free Software Foundation.
# 
# The above named program is distributed in the hope that it will be 
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this work; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
# 
# ========== Copyright Header End ============================================

$VCS_HOME/bin/vcs \
-Xstrict=1 -notice +nbaopt +nospecify +notimingcheck +vcsd \
-l compile.log \
-f $1 \
+vc+abstract +v2k 

# include for fsdb dump 
# -P $NOVAS_HOME/share/PLI/vcsd/SOLARIS2/vcsd.tab \
# $NOVAS_HOME/share/PLI/vcsd/SOLARIS2/pli.a +vcsd
