
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.2 EDK_J.12.5.1
* DO NOT EDIT.
*
* Copyright (c) 2006 Xilinx, Inc.  All rights reserved.
*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xlltemac.h"

/*
* The configuration table for devices
*/

XLlTemac_Config XLlTemac_ConfigTable[] = {
	{
	 XPAR_XPS_LL_TEMAC34_0_DEVICE_ID,
	 XPAR_XPS_LL_TEMAC34_0_BASEADDR,
	 1,
	 1,
	 1,
	 XPAR_XPS_LL_TEMAC34_0_LLINK0_CONNECTED_TYPE,
	 XPAR_XPS_LL_TEMAC34_0_LLINK0_CONNECTED_BASEADDR,
	 0,0,0,0
	}
};
