#!/bin/sh
# ========== Copyright Header Begin ==========================================
# 
# OpenSPARC T1 Processor File: micronddr_patch
# Copyright (c) 2006 Sun Microsystems, Inc.  All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES.
# 
# The above named program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License version 2 as published by the Free Software Foundation.
# 
# The above named program is distributed in the hope that it will be 
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this work; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
# 
# ========== Copyright Header End ============================================

# Change address orientation
sed "s/Bank_addr\,\ Rows_addr\,\ Cols_addr/Rows_addr\,\ Bank_addr\,\ Cols_addr/" ddr.v > ddr.v.stemp
mv ddr.v.stemp ddr.v

sed '/Timing parameters based on Speed Grade/a\
    parameter binfilename = "a";' ddr_parameters.vh > ddr_parameters.vh.stemp
mv ddr_parameters.vh.stemp ddr_parameters.vh


sed "s/endmodule/initial\ begin\ \$readmemh\(binfilename\,mem_array\)\;\ end\ \ endmodule/" ddr.v > ddr.v.stemp
mv ddr.v.stemp ddr.v



